using Serilog;
using solum.core;
using solum.core.dataprocess;
using solum.core.smtp;
using solum.core.storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace solum
{
    class Program
    {
        //static ILogger Log = Log.ForContext(typeof(Program));

        static void Main(string[] args)
        {
            //RunEmailTest();
            RunKeyValueTest();            
            // Server.RunServer();
            // RunProcessTests();
        }

        static void RunEmailTest(int emailsToGenerate = 1)
        {
            using (var server = Server.Load("./config/email-test.config.json"))
            {
                server.Start();
                var emailService = server.Service<EmailService>(true);

                for (var lcv = 1; lcv <= emailsToGenerate; lcv++)
                {
                    emailService.Email("brad.serbu@geofeedia.com", "Test email #{0}".format(lcv), "This is the {0} email generated by the email test service".format(lcv));
                }

                server.Stop();
            }
        }

        static void RunKeyValueTest()
        {
            var db = "test-db";
            var key = "name";
            var value = "Brad Serbu";

            string savedValue;

            using (var server = Server.Current)
            {
                var store = server.Storage.OpenKeyValueStore(db);
                store.Set(key, value);
                store.Get(key, out savedValue);
                store.Remove(key);                
            }

            Console.WriteLine("Hello, {0}!", savedValue);
        }

        static void RunProcessTests()
        {
            var source = SayHello(10);
            singleChainedProcess(source).Run();
            manyStepParallelProcess(source).Run();
            mixedProcess(source).Run();

            //var count = 0;
            //process.OnEntryProcessed += (_, entry) =>
            //{
            //    Log.Information("Processed entry #{0:N}", ++count);
            //};

            //process.OnFinished += (_, __) =>
            //{
            //    Log.Information("Processed {0} items.", count);
            //};

            //process.Run();
        }

        static DataProcess singleChainedProcess<T>(IEnumerable<T> source)
        {
            var count = 0;
            var process = DataProcess.With(SayHello(10))
                                     .Do(hello => Log.Information(hello))
                                     .Then(_ =>
                                     {
                                         Log.Information("Waiting 100 ms...");
                                         Thread.Sleep(100);
                                     })
                                     .Then(hello =>
                                     {
                                         Log.Information("\t#{0:N}", ++count);

                                         return new
                                         {
                                             message = hello,
                                             count = count
                                         };
                                     })
                                    .Then(hello => Log.Information("\t {0}", hello))
                                    .Process;

            return process;
        }
        static DataProcess manyStepParallelProcess<T>(IEnumerable<T> source)
        {
            var count = 0;
            var process = DataProcess.With(SayHello(10))
                                     .Do(hello => Log.Information(hello))
                                     .Do(_ =>
                                     {
                                         Log.Information("Waiting 100 ms...");
                                         Thread.Sleep(100);
                                     })
                                     .Do(hello =>
                                     {
                                         Log.Information("\t#{0:N}", ++count);

                                         return new
                                         {
                                             message = hello,
                                             count = count
                                         };
                                     })
                                    .Then(hello => Log.Information("\t {0}", hello))
                                    .Process;

            return process;
        }
        static DataProcess mixedProcess<T>(IEnumerable<T> source)
        {
            var count = 0;
            var process = DataProcess.With(SayHello(10))
                                     .Do(hello => Log.Information(hello))
                                     .Do(_ =>
                                     {
                                         Log.Information("Waiting 100 ms...");
                                         Thread.Sleep(100);
                                     })
                                     .Do(hello =>
                                     {
                                         Log.Information("\t#{0:N}", ++count);

                                         return new
                                         {
                                             message = hello,
                                             count = count
                                         };
                                     })
                                    .Then(hello => Log.Information("\t {0}", hello))
                                    .Process;

            return process;
        }

        static IEnumerable<string> SayHello(int count)
        {
            for (var lcv = 0; lcv < count; lcv++)
                yield return "Hello World!";
        }
    }
}
